### ISSUE TITLE
Investigate Visual Studio 2015 Community / Premium support

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2-vsixextensions#23]
Extensions fail to create a new project once Visual Studio 2015 Community is used. Needs to be investigated.

**Comment by AndreyBespamyatnov** [comment]
On Enterprise  too, doesn't work.

**Comment by SubPointSupport** [comment]
What is the error? Something related to the paths?

**Comment by milleraa** [comment]
---------------------------
Microsoft Visual Studio
---------------------------
The process cannot access the file 'C:\Users\spinstall\AppData\Local\Microsoft\VisualStudio\14.0\VTC\7fef15757bbb1e3961446497dabc508e\~PC\ProjectTemplates\CSharp\SPMeta2\SPMeta2.VS.CSharp.project.zip\_project.vstemplate' because it is being used by another process.
---------------------------
OK   
---------------------------

I've got this message.

**Comment by SubPointSupport** [comment]
Fixed, will be in the upcoming update in Feb 6, 2017.
